# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

I suggest you implement *constraint satisfaction* as it is described in the unit material. You can use the code you have previously been given as a guide. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%).

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [ ]:
import numpy as np

# Load sudokus
sudoku = np.load("data/hard_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/hard_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[8], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[8])

## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
import numpy as np
sudokus = np.load("/Users/seena/PycharmProjects/untitled/AI/hard_puzzle.npy")
sudoku = sudokus[9]

digits = '123456789'
rows = 'ABCDEFGHI'


def cross(A, B):
    # Returns cross-product of A and B
    return [a + b for a in A for b in B]

#Define units of each row, column and 3x3 box for searching
rowList = []
colList = []
boxList = []
for i in rows:
    rowList.append(cross(i, digits))
for i in digits:
    colList.append(cross(rows, i))
for i in ['ABC', 'DEF', 'GHI']:
    for j in ['123', '456', '789']:
        boxList.append(cross(i, j))

#UNIT = Row, Column and Box for a given square
unitList = rowList + colList + boxList  # Combine arrays for each row, column and box


squares = cross(rows, digits)
#Using list comprehension to improve readability-----------
#Create dictionary of all possible units for rapid searching
unitDict = dict((box, [unit for unit in unitList if box in unit]) for box in squares)
#Create dictionary of all possible peers for rapid searching using set subtraction to remove duplicates
peerDict = dict((box, set(sum(unitDict[box], [])) - set([box])) for box in squares)

#Verify that the sudoku is valid
def valid(sudoku, end): #-> Boolean
    def rowChecker(s):
        #Check array for consecutive nonzero digits
        matrix = s
        for i in range(0, len(s)):
            for j in range(0, len(s)-1):
                if s[i][j] == s[i][j+1] and s[i][j] != 0:
                    #Return False (invalid) if consecutive nonzero values detected
                    return False
                if end:
                    #Extra check before solved sudoku is output
                    if len(matrix[i]) != len(set(matrix[i])): #Checks for duplicates
                        return False
        return True

    #Transpose to convert rows to columns, and check again using same method
    transposed = [[sudoku[j][i] for j in range(len(sudoku))] for i in range(len(sudoku[0]))]
    #Validate rows and columns
    if rowChecker(sudoku) and rowChecker(transposed):
        return True
    return False


# Converts grid into dictionary of possible values
def sudoku_solver(sudoku):
    sudokuDict = {}
    if valid(sudoku, False):
        for i, row in enumerate(sudoku):  # i = row number
            for j, val in enumerate(row):  # j = column number
                # Define square ID (A1...I9)
                square = rows[i] + digits[j]
                # If empty space detected
                if val == 0:
                    # Assign possible values 1-9 to dictionary
                    sudokuDict[square] = '123456789'
                else:
                    # Otherwise, assign provided value to dictionary
                    sudokuDict[square] = str(sudoku[i][j])
        #Pass dictionary to solve function
        result = solve(sudokuDict)
        #Handle returned tuple: (Bool, Dictionary)
        if result[0]:
            return output(result[1])
        elif not result[0]:
            return (np.ones((9,9)) * -1)
    else:
        return (np.ones((9,9)) * -1)


def eliminate(sDict):
    # iterate through grid dictionary
    for i, (key, val) in enumerate(sDict.items()):
        # If square's dictionary contains more than one item
        if len(val) > 1:
            peers = peerDict[key] #Get all intersecting cells using square's key (e.g. A1)
            peer_values = []
            #Get the values of the intersecting cells
            for i in peers:
                if len(sDict[i]) == 1:
                    peer_values.append(sDict[i])
            #Convert to set to allow for set subtraction and automatic duplication removal
            peer_values = set(peer_values)
            #Eliminate values already in the peer list
            sDict[key] = ''.join(set(sDict[key]) - peer_values)
    return sDict


def naked_single(sDict):
    # Iterate through each unit
    for i in unitList:
        for j in digits:
            # List comprehension: adds every occurance of each digit in a unit into an array
            apps = [square for square in i if j in sDict[square]]
            # Sets to sole dictionary value if only appears once in unit
            if len(apps) == 1:
                sDict[apps[0]] = j
    return sDict


def apply(sDict):
    stuck = False
    while not stuck:
        #Check number of values in dictionary before solving
        arr = []
        for i in enumerate(sDict.keys()):
            if len(i) == 1:
                arr.append(i)
        before = len(arr)

        # Apply solving strategies
        sDict = eliminate(sDict)
        sDict = naked_single(sDict)

        #Check number of values in dictionary after solving
        arr = []
        for i in enumerate(sDict.keys()):
            if len(i) == 1:
                arr.append(i)
        after = len(arr)

        # Program is stuck if no values have changed
        stuck = before == after

        #Check if any squares have 0 candidates
        if len([box for box in sDict.keys() if len(sDict[box]) == 0]):
            return False #currently unsolveable
    return sDict


def solve(sDict):
    sDict = apply(sDict)
    if sDict == False:
        return (False, sDict)

    # If all squares contain a single value, return solved dictionary
    if all(len(v) == 1 for k,v in sDict.items()):
        return (True, sDict)

    # Identify square with least number of possibilities
    length, k = min((len(val), key) for key, val in sDict.items() if len(val) > 1)

    for i in sDict[k]:
        #Recursively set up new boards with alternate configurations
        newBoard = dict(list(sDict.items()))
        #add new config to board
        newBoard[k] = i
        #Attempt to solve new config
        re_solve = solve(newBoard)
        try:
            #Return solved board
            if re_solve[0]:
                return re_solve
        except:
            return (False, sDict)
    return (False, sDict)



def output(sDict):
    outArray = []
    #Guard statement: Check that all squares contain a single candidate
    if all(len(v) == 1 for k,v in sDict.items()):
        #Formatting: Convert dictionary back into NumPy array
        for i in sDict:
            outArray.append(int(sDict[i]))

        #Split array of dictionary values into rows
        slices = [outArray[x:x + 9] for x in range(0, len(outArray), 9)]
        #Convert rows into 2D array and return
        outarr = np.asarray(slices)
        if valid(outarr, True): #Final validation check
            return np.asarray(slices)
        else:
            return (np.ones((9,9)) * -1)




All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 30 seconds each on the test machine to count as successful, but you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [3]:
import numpy as np
SKIP_TESTS = False

if not SKIP_TESTS:
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            print("attempting to solve...")
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")
            
        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break

Testing very_easy sudokus
This is very_easy sudoku number 0
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]]
attempting to solve...
This is your solution for very_easy sudoku number 0
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0011520000000000419 seconds to solve.

This is very_easy sudoku number 1
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]]
attempting to solve...
This is your solution for very_easy sudoku number 1
[[4 9 3 1 5 2 6 7 8]
 [8 6 2 7 4 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 5 

This is your solution for hard sudoku number 9
[[-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]]
Is your solution correct?
No, the correct solution is:
[[5. 9. 4. 2. 8. 7. 1. 3. 6.]
 [1. 2. 8. 3. 6. 9. 4. 5. 7.]
 [7. 6. 3. 5. 1. 4. 8. 2. 9.]
 [9. 7. 2. 8. 3. 5. 6. 1. 4.]
 [4. 8. 6. 7. 2. 1. 5. 9. 3.]
 [3. 5. 1. 9. 4. 6. 7. 8. 2.]
 [8. 3. 5. 6. 7. 2. 9. 4. 1.]
 [2. 4. 7. 1. 9. 8. 3. 6. 5.]
 [6. 1. 9. 4. 5. 3. 2. 7. 8.]]
This sudoku took 0.025944999999999996 seconds to solve.

This is hard sudoku number 10
[[0 0 0 6 0 0 2 0 0]
 [0 0 0 0 0 9 0 6 0]
 [0 8 0 0 0 5 0 0 3]
 [1 0 0 4 0 0 9 0 0]
 [8 3 0 0 0 0 0 0 0]
 [0 2 0 0 0 6 0 0 0]
 [0 0 0 0 6 0 0 0 0]
 [2 5 0 3 0 7 0 9 0]
 [0 0 1 0 0 0 0 8 4]

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [ ]:
import sys
import pathlib

fail = False;

if not SKIP_TESTS:
    fail = True;
    print("You must set the SKIP_TESTS constant to True in the cell above.")
    
p1 = pathlib.Path('./readme.txt')
p2 = pathlib.Path('./readme.md')
if not (p1.is_file() or p2.is_file()):
    fail = True;
    print("You must include a separate file called readme.txt or readme.md in your submission.")
    
p3 = pathlib.Path('./sudoku.ipynb')
if not p3.is_file():
    fail = True
    print("This notebook file must be named sudoku.ipynb")
    
if "sudoku_solver" not in dir():
    fail = True;
    print("You must include a function called sudoku_solver which accepts a numpy array.")
else: 
    sudoku = np.load("data/very_easy_puzzle.npy")[0]
    solution = np.load("data/very_easy_solution.npy")[0]

    if not np.array_equal(sudoku_solver(sudoku), solution):
        print("Warning:")
        print("Your sudoku_solver function does not correctly solve the first sudoku.")
        print()
        print("Your assignment is unlikely to get any marks from the autograder. While we will")
        print("try to check it manually to assign some partial credit, we encourage you to ask")
        print("for help on the forum or directly to a tutor.")
        print()
        print("Please use the readme file to explain your code anyway.")
    
if fail:
    print()
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
    print("assignment page, without changing any filenames.")
    print()
    print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")

In [ ]:
# This is a TEST CELL. Do not delete or change.